---
- name: Hardening
  hosts: all
  become: true
  tasks:
    - name: Ensure SSH protocol v2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
    
    - name: Remove unused packages
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - telnet
        - rsh-server
